Add a confirmation prompt to repods.

diff --git a/scripts/repods b/scripts/repods
--- a/scripts/repods
+++ b/scripts/repods
@@ -3,6 +3,21 @@
 # This script will COMPLETELY refresh the PODS codebase and container.
 # THIS WILL UNDO ALL UNCOMMITTED CHANGES!
 
+# Confirm that the user wants to do this...
+read -r -p "PODS will be rebuilt. You will lose all data and uncommitted changes. Are you sure? [Y/n] " input
+case $input in
+      [yY][eE][sS]|[yY])
+            echo "Rebuilding PODS..."
+            ;;
+      [nN][oO]|[nN])
+            exit 0
+            ;;
+      *)
+            echo "Invalid input..."
+            exit 1
+            ;;
+esac
+
 # Get this script's path and parent directory.
 SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
 PARENTPATH="$(dirname $SCRIPTPATH)"
